[tool.poetry]
name = "egi_pynetstation"
version = "2.1.0"
description = "EGI EEG NetStation Interface with Precision Timing"
authors = ["Joshua B. Teves <jbtevespro@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://egi-pynetstation.readthedocs.io/en/latest/"
repository = "https://github.com/nimh-sfim/egi-pynetstation"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
pytest = "*"
flake8 = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
